### ISSUE TITLE
IndexOutOfBoundsException if second run of the scenario takes less than 60 seconds

### ISSUE THREAD

**Issue by jdurani** [PerfCake/PerfCake#381] opened 2017-05-05 06:26 UTC
I run scenario which generates loads for 60 seconds. Then I run same scenario but change it to generate load for only 10 seconds. Second run ends with IOOBE [1] during merging charts of two runs.
I am not 100% sure what is the threshold, but I am able to reproduce this with 60s and 10s.

Environment:
PerfCake: 7.4
Generator: DefaultMessageGenerator
Sender: JdbcSender

[1]
```
08:13:13,475 FATAL [ScenarioExecution] Error running scenario: 
org.perfcake.PerfCakeException: Error generating messages: 
	at org.perfcake.scenario.Scenario.run(Scenario.java:143) ~[perfcake-7.4.jar:?]
	at org.perfcake.ScenarioExecution.executeScenario(ScenarioExecution.java:314) [perfcake-7.4.jar:?]
	at org.perfcake.ScenarioExecution.main(ScenarioExecution.java:105) [perfcake-7.4.jar:?]
	at org.jboss.qe.dv.performance.PerformanceUtils.runTest(PerformanceUtils.java:65) [test-classes/:?]
	at org.jboss.qe.dv.performance.EnginePerformanceTest.engineTest(EnginePerformanceTest.java:26) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0-internal]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86) [testng-6.9.10.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643) [testng-6.9.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820) [testng-6.9.10.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128) [testng-6.9.10.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.9.10.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.9.10.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:782) [testng-6.9.10.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:632) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:268) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.9.10.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.9.10.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244) [testng-6.9.10.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169) [testng-6.9.10.jar:?]
	at org.testng.TestNG.run(TestNG.java:1064) [testng-6.9.10.jar:?]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70) [surefire-testng-2.9.jar:2.9]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108) [surefire-testng-2.9.jar:2.9]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111) [surefire-testng-2.9.jar:2.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0-internal]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164) [surefire-api-2.9.jar:2.9]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110) [surefire-booter-2.9.jar:2.9]
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172) [surefire-booter-2.9.jar:2.9]
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104) [surefire-booter-2.9.jar:2.9]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70) [surefire-booter-2.9.jar:2.9]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0-internal]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0-internal]
	at org.perfcake.reporting.destination.c3chart.C3ChartData.combineWith(C3ChartData.java:204) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.combineCharts(C3ChartReport.java:236) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.analyzeMatchingCharts(C3ChartReport.java:192) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.destination.c3chart.C3ChartReport.createReport(C3ChartReport.java:90) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.destination.c3chart.C3ChartHelper.compileResults(C3ChartHelper.java:152) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.destination.ChartDestination.close(ChartDestination.java:168) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.reporter.AbstractReporter$$Lambda$34/425107133.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0-internal]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1140) ~[?:1.8.0-internal]
	at org.perfcake.reporting.reporter.AbstractReporter.stop(AbstractReporter.java:351) ~[perfcake-7.4.jar:?]
	at org.perfcake.reporting.ReportManager$$Lambda$33/1629759610.accept(Unknown Source) ~[?:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0-internal]
	at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:404) ~[?:1.8.0-internal]
	at org.perfcake.reporting.ReportManager.stop(ReportManager.java:360) ~[perfcake-7.4.jar:?]
	at org.perfcake.message.generator.AbstractMessageGenerator.setStopTime(AbstractMessageGenerator.java:203) ~[perfcake-7.4.jar:?]
	at org.perfcake.message.generator.DefaultMessageGenerator.shutdown(DefaultMessageGenerator.java:187) ~[perfcake-7.4.jar:?]
	at org.perfcake.message.generator.DefaultMessageGenerator.generate(DefaultMessageGenerator.java:227) ~[perfcake-7.4.jar:?]
	at org.perfcake.scenario.Scenario.run(Scenario.java:141) ~[perfcake-7.4.jar:?]
	... 37 more
```

**Comment by pmacik** [comment] 2017-05-12 12:19
@jdurani  Thanks for reporting this.
It is most likely a duplicate of https://github.com/PerfCake/PerfCake/issues/376 that is fixed in v7.5 which was released yesterday.

Could you please try the new version?
Thanks.

**Comment by jdurani** [comment] 2017-05-12 13:15
It looks like duplicate. I tried same steps and no exception has been thrown.

**Comment by pmacik** [comment] 2017-05-17 08:11
OK great, thanks for checking. Closing as a duplicate.

**Closed as completed by pmacik** 2017-05-17 08:11 UTC
Labels: duplicate
